version: "3.4"

services:
  web-app:
    build:
      context: ./WebApp/persa-learn
      dockerfile: Dockerfile.test
    volumes:
      - ./WebApp/persa-learn/src:/app/src
      - "./test_reports:/test_reports"
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=api:8080,db:3306
    ports:
      - "3000:3000"

    # dockerfile: ./WebApp/persa-learn/Dockerfile
  api:
    build:
      args:
        NODE_ENV: development
      context: ./node js RESTful API
      dockerfile: Dockerfile.dev

    volumes:
      - ./node js RESTful API/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
