version: "3.4"

services:
  web-app:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./WebApp/persa-learn/build:/web
    restart: always
    # environment:
    #   - apiAdd=value
    # build:
    #   context: ./WebApp/persa-learn
    #   dockerfile: Dockerfile.prod
    # ./WebApp/persa-learn
    ports:
      - "3000:3000"
    # dockerfile: ./WebApp/persa-learn/Dockerfile
